upstream flask_upstream {
    server flask1:8000;
    server flask2:8000;
}

server {
    listen 80;

    location /static/ {
        alias /app/static/;
    }

    location / {
        proxy_pass http://flask_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
